### ISSUE TITLE
After upgrade from vscode-java v0.77.0 to v0.78.0 can't debug tests

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-java-debug#995]
After upgrade [vscode-java](https://github.com/redhat-developer/vscode-java) from v0.77.0 to v0.78.0 can't debug tests, only execute them

##### Environment
- Operating System: Linux
- JDK version: 11
- Visual Studio Code version: 1.55.2
- Java extension version: 0.78.0

##### Steps To Reproduce
1. Open a maven project with JUnit tests
2. Try run the test in debug mode

##### Current Result
An error message appears and the test can't be run

##### Expected Result
Test is run stopping at any break point

##### Additional Informations
I I downgrade to version 0.77.0 everything works as expected.

The error message in the log is: 
`java.lang.NoSuchMethodError: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'`

see: https://github.com/redhat-developer/vscode-java/issues/1915

**Comment by kjq** [comment]
I get the same issue.  Wasted the whole day till I came across this.

**Comment by rgrunber** [comment]
```
[Error - 4:06:47 PM] Apr 29, 2021, 4:06:47 PM [error response][launch]: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'
'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'
java.lang.NoSuchMethodError: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'
	at com.microsoft.java.debug.plugin.internal.AdvancedLaunchingConnector$AdvancedStringArgumentImpl.<init>(AdvancedLaunchingConnector.java:124)
	at com.microsoft.java.debug.plugin.internal.AdvancedLaunchingConnector.defaultArguments(AdvancedLaunchingConnector.java:47)
	at com.microsoft.java.debug.core.DebugUtility.launch(DebugUtility.java:205)
	at com.microsoft.java.debug.core.DebugUtility.launch(DebugUtility.java:97)
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.launch(LaunchWithDebuggingDelegate.java:180)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.launch(LaunchRequestHandler.java:242)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handleLaunchCommand(LaunchRequestHandler.java:142)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handle(LaunchRequestHandler.java:81)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:89)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2305)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:88)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Maybe the java-debug LS needs to be rebuilt against the latest JDT-LS. I know that between 0.77.0 and 0.78.0, JDT-LS bumped it's target platform from 4.19 to 4.20M1, which would have included https://github.com/eclipse/eclipse.jdt.debug/commit/703498f768b73a3f3ca26aba7e74da2c0e6807c0#diff-9edaaaad5de823a144b40d3074650b42973c116b4c595682ea98b2a94aa24c99 .

**Comment by fbricon** [comment]
The problem is caused by https://github.com/eclipse/eclipse.jdt.debug/commit/703498f768b73a3f3ca26aba7e74da2c0e6807c0#diff-9edaaaad5de823a144b40d3074650b42973c116b4c595682ea98b2a94aa24c99R188

the java-debug plugin needs to be recompiled against the newer build indeed.

**Comment by snjeza** [comment]
@rubensa @kjq @rgrunber @fbricon you can try https://github.com/snjeza/vscode-test/raw/master/vscode-java-debug-0.33.1.vsix

**Comment by rubensa** [comment]
Checked!  It works!

Thanks @snjeza 

Any ETA for a new version to be available in the Marketplace?

**Comment by saumilsdk** [comment]
How did you make it work?

**Comment by testforstephen** [comment]
I'm fixing it now, there will be a hotfix today.

**Comment by saumilsdk** [comment]
Ok temporarily I have locally downgraded version to 0.77.0.

![image](https://user-images.githubusercontent.com/8816702/116659309-09940a80-a9af-11eb-9991-f5aff44a28fa.png)

![image](https://user-images.githubusercontent.com/8816702/116659323-0ef15500-a9af-11eb-8c8a-d8149b0c03b8.png)

**Comment by AYiXi** [comment]
> I'm fixing it now, there will be a hotfix today.

thx, It waste me so much time, I reinstalled old version several hours later, and close `extension.autoUpdate` to `false`

**Comment by testforstephen** [comment]
Hi, I just released a hotfix release 0.33.1 for debugger. It will work with both vscode-java@0.77.0 and 0.78.0. Please have a try. thanks.

**Comment by rubensa** [comment]
> Hi, I just released a hotfix release 0.33.1 for "Debugger for Java" extension. It will work with both vscode-java@0.77.0 and 0.78.0. Please have a try. thanks.

Curious that is already published on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) but not yet on [Github](https://github.com/microsoft/vscode-java-debug/releases)

**Comment by AYiXi** [comment]
nbnb!!

**Comment by testforstephen** [comment]
> Curious that is already published on the [Marketplace](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) but not yet on [Github](https://github.com/microsoft/vscode-java-debug/releases)
> 

@rubensa the vsix is added to [Github](https://github.com/microsoft/vscode-java-debug/releases).

**Comment by dhirenpratap** [comment]
Thanks a Lot. I wasted 4 hours on this yesterday.

**Comment by MxD-js** [comment]
Also issue in cdr/code-server, downgrading to 0.77 fixes it for now until 1.55 is released w/ code-server to apply update. Thanks.
